Add mp (mystery-person) as a valid default
pabluk/libgravatar pull request #3
Opened 2020-06-09 09:42 UTC by snowjet

According to the Gravatar documentation - http://en.gravatar.com/site/implement/images/ -  mp (mystery-person) is a valid default. This has probably replaced mm. Left mm, for backwards compat.

2020-06-09 21:34 UTC, pabluk requested changes
Awesome! yes, I didn't know about `mp` but of course it would be great to add it here.

Just before merge could you please also update the docstring in this line [libgravatar/__init__.py#L80](https://github.com/pabluk/libgravatar/blob/93496c45d0b6ad5c839aab11e9e4d4844e77453a/libgravatar/__init__.py#L80) in order to keep the documentation site up to date.

And please don't hesitate to update this PR and add your name in the into the "Author and contributors" section here https://github.com/pabluk/libgravatar/blob/master/README.rst#author-and-contributors

After that I'll try to merge and release a new version on pypi asap.

Thanks!

2020-06-09 22:35 UTC, snowjet commented
No problem. In my haste, I skipped the docstring. All updated. :-).

Thanks.

2020-06-10 07:12 UTC, pabluk approved these changes

2020-06-10 07:14 UTC, merged

2020-06-10 07:14 UTC, pabluk commented
Thanks @snowjet for your contribution!

2020-06-10 22:26 UTC, pabluk commented
Just for the record, a new 0.2.4 version has been published on https://pypi.org/project/libgravatar/ and the documentation is up to date https://libgravatar.readthedocs.io/en/latest/#libgravatar.Gravatar.get_image :tada: